Graphics/assets/pages/my-life-aquatic-master/my-life-aquatic-master/config/routes.rb
MyAquarium::Application.routes.draw do
  resources :aquaria

  root :to => 'aquaria#index'

  match "/pusher/auth" => 'pusher#auth'
end

Graphics/assets/pages/my-life-aquatic-master/my-life-aquatic-master/app/models/aquarium.rb
class Aquarium < ActiveRecord::Base
  attr_accessible :name
end

Graphics/assets/pages/my-life-aquatic-master/my-life-aquatic-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Graphics/assets/pages/my-life-aquatic-master/my-life-aquatic-master/app/controllers/aquaria_controller.rb
class AquariaController < ApplicationController
  # GET /aquaria
  # GET /aquaria.json
  def index
    @aquaria = Aquarium.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @aquaria }
    end
  end

  # GET /aquaria/1
  # GET /aquaria/1.json
  def show
    @aquarium = Aquarium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @aquarium }
    end
  end

  # GET /aquaria/new
  # GET /aquaria/new.json
  def new
    @aquarium = Aquarium.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @aquarium }
    end
  end

  # GET /aquaria/1/edit
  def edit
    @aquarium = Aquarium.find(params[:id])
  end

  # POST /aquaria
  # POST /aquaria.json
  def create
    @aquarium = Aquarium.new(params[:aquarium])

    respond_to do |format|
      if @aquarium.save
        format.html { redirect_to @aquarium, notice: 'Aquarium was successfully created.' }
        format.json { render json: @aquarium, status: :created, location: @aquarium }
      else
        format.html { render action: "new" }
        format.json { render json: @aquarium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /aquaria/1
  # PUT /aquaria/1.json
  def update
    @aquarium = Aquarium.find(params[:id])

    respond_to do |format|
      if @aquarium.update_attributes(params[:aquarium])
        format.html { redirect_to @aquarium, notice: 'Aquarium was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @aquarium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aquaria/1
  # DELETE /aquaria/1.json
  def destroy
    @aquarium = Aquarium.find(params[:id])
    @aquarium.destroy

    respond_to do |format|
      format.html { redirect_to aquaria_url }
      format.json { head :no_content }
    end
  end
end

Graphics/assets/pages/my-life-aquatic-master/my-life-aquatic-master/app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  protect_from_forgery :except => :auth # stop rails CSRF protection for this action
  
  def auth
    response = Pusher[params[:channel_name]].authenticate(params[:socket_id])
    render :json => response
  end
end

Graphics/assets/pages/my-life-aquatic-master/my-life-aquatic-master/app/helpers/application_helper.rb
module ApplicationHelper
  def render_pusher_key
  	if Rails.env.production?
  	  return "'e82f5cd951da24bf59a4'"
  	else
      return "'14bbe7d2ac1504c5683f'"
    end
  end
end

Graphics/assets/pages/my-life-aquatic-master/my-life-aquatic-master/app/helpers/aquaria_helper.rb
module AquariaHelper
end

Graphics/assets/pages/my-life-aquatic-master/my-life-aquatic-master/app/views/aquaria/_form.html.erb
<%= form_for(@aquarium) do |f| %>
  <% if @aquarium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aquarium.errors.count, "error") %> prohibited this aquarium from being saved:</h2>

      <ul>
      <% @aquarium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Graphics/assets/pages/my-life-aquatic-master/my-life-aquatic-master/app/views/aquaria/edit.html.erb
<h1>Editing aquarium</h1>

<%= render 'form' %>

<%= link_to 'Show', @aquarium %> |
<%= link_to 'Back', aquaria_path %>

Graphics/assets/pages/my-life-aquatic-master/my-life-aquatic-master/app/views/aquaria/index.html.erb
<div id="pond-container">
    <div id="instructions">
      <div id="instructions1" class="instructions">
        Welcome to the Aquarium. Eat the fish food so you don't get too skinny!
      </div>
      <div id="instructions2" class="instructions">
        Invite your friends to swim together :)
      </div>
    </div>

    <div id="credits">
      <div>
        koi designed by 
        <a href="http://nardove.com/" target="_blank">nardove</a>
        <br>
        interactive aquarium by 
        <a href="http://twitter.com/sunahsuh" target="_blank">sunah suh</a> 
        and 
        <a href="http://twitter.com/davidleibovic" target="_blank">david leibovic</a>
      </div>
    </div>


  <canvas id="mycanvas" data-processing-sources="processing/pond.pjs processing/Fish.pjs processing/Boid.pjs processing/Flagellum.pjs processing/Bubble.pjs processing/Food.pjs"></canvas>

</div>

<div id="gameOverDialog" title="You didn't feed your fish!">
    <p>Your fish has been neglected. It faded away due to starvation! Poor fishy.</p>
    <p>Eat the fish food to avoid getting too skinny!</p>
</div>

<!-- <div id="debugger" style="border: 1px solid black; height: 30px; width: 100%"></div> -->

<script type="text/javascript">
  // the reference to the processing sketch
  var pjs;
  // the id of the repeated update events that each local fish makes
  var intervalId;
  var gulp = new buzz.sound("audio/gulp", {
    formats: [ "ogg", "mp3"]
  });
  gulp.setVolume(100);


  channel.bind('pusher:subscription_error', function(status) {
    alert("pusher subscription failed: " + status);
  });

  // bind to the repeated updates that each local fish makes about itself.
  channel.bind('client-update', function(data) {
    pjs.updateRemoteFish(data.myLocation, data.mousePosition, data.stripeColor, data.id, data.maxSpeed, data.maxForce, data.bodySizeW, data.bodySizeH, data.velocity, data.canonicalUnModdedLocation, data.originalBodySizeW,
      data.originalBodySizeH, data.startFade);
    
    pjs.updateRemoteFood(data.foodLocation, data.foodVelocity, data.foodIsDead, data.foodId, 
      data.foodColor, data.foodAge, data.foodIsDummy);
  });

  // bind to the event that a remote fish ate a food
  channel.bind('client-my-fish-ate', function(data) {
    gulp.play();
    pjs.foodEatenByRemoteFish(data.foodEatenId, data.myFishId);
  });

  // create the repeated pusher updates
  function createRepeatedUpdateEvents() {
    if(pjs != null) {
      intervalId = setInterval(function(){
        sendUpdate();
        //printDebugInfo();
      }, 100); // send every 100 milliseconds if position has changed
      pjs.setPusherUpdateIntervalId(intervalId);
    }
    else
      setTimeout(createRepeatedUpdateEvents,250);
  }

  // obtain a reference to the processing sketch
  function getPjsInstance() {
    var bound = false;
    pjs = Processing.getInstanceById('mycanvas');
    if(pjs != null)
      bound = true;
    if(!bound)
      setTimeout(getPjsInstance, 250);
  } 

  // the repeated update where each local fish tells others about itself
  function sendUpdate(){
    var myFish = pjs.getMyFish();
    var myFood = pjs.getMyFood();
    channel.trigger("client-update",
      {
        myLocation: myFish.getLocation(),
        mousePosition: myFish.getMousePosition(),
        stripeColor: myFish.getStripeColor(),
        id: myFish.getId(),
        maxSpeed: myFish.getMaxSpeed(),
        maxForce: myFish.getMaxForce(),
        bodySizeW: myFish.getBodySizeW(),
        bodySizeH: myFish.getBodySizeH(),
        velocity: myFish.getVelocity(),
        canonicalUnModdedLocation: myFish.getCanonicalUnModdedLocation(),
        originalBodySizeW: myFish.getOriginalBodySizeW(),
        originalBodySizeH: myFish.getOriginalBodySizeH(),
        startFade: myFish.getStartFade(),

        foodLocation: myFood.getLocation(),
        foodVelocity: myFood.getVelocity(),
        foodIsDead: myFood.getIsDead(),
        foodId: myFood.getId(),
        foodColor: myFood.getColor(),
        foodAge: myFood.getAge(),
        foodIsDummy: myFood.getIsDummy(),
      });
  }

  function printDebugInfo() {
    myFish = pjs.getMyFish();
    document.getElementById('debugger').innerHTML = myFish.getId();
  } 
</script>

<script>
  $(document).ready(function() {
    $('#instructions1').delay(3000).fadeIn(3500)
      .fadeOut(3500, function() {
        $('#instructions1').text("It gets lonely swimming alone...").
          fadeIn(3500, function() {
            $('#instructions2').fadeIn(3500);
          });
      });
    setTimeout(function(){$(".instructions").fadeOut(3500);},28000);

   getPjsInstance();
   createRepeatedUpdateEvents();
  });
</script>

<audio autoplay loop>
  <source src="audio/swimming-music.ogg" type="audio/ogg" />   
  <source src="audio/swimming-music.mp3" type="audio/mpeg" />
</audio>

Graphics/assets/pages/my-life-aquatic-master/my-life-aquatic-master/app/views/aquaria/new.html.erb
<h1>New aquarium</h1>

<%= render 'form' %>

<%= link_to 'Back', aquaria_path %>

Graphics/assets/pages/my-life-aquatic-master/my-life-aquatic-master/app/views/aquaria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @aquarium.name %>
</p>


<%= link_to 'Edit', edit_aquarium_path(@aquarium) %> |
<%= link_to 'Back', aquaria_path %>

Graphics/assets/pages/my-life-aquatic-master/my-life-aquatic-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>my life aquatic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <script src="http://js.pusher.com/1.12/pusher.min.js"></script>
  <script type="text/javascript">
    var pusher = new Pusher(<%= render_pusher_key %>);
    var channel = pusher.subscribe("private-aquarium"); 
  </script>
  <!-- could not put the processing.js inside the asset js pipeline because uglifier had issues minifying it -->
  <script src="javascripts/processing-1.4-release-candidate.js"></script>
  <%= javascript_include_tag "application" %>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.js"></script>
  <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/themes/smoothness/jquery-ui.css">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>